import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";

import { SidebarProvider } from "@/components/ui/sidebar";
import { TinybirdProvider } from "@/contexts/TinybirdContext";
import Sidebar from "@/components/Sidebar";

import { Providers } from "./providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <SidebarProvider defaultOpen>
            <TinybirdProvider>
              <Sidebar />
              <main className="w-full px-3 py-10">
                <div className="container mx-auto max-w-screen-xl">
                  {children}
                </div>
              </main>
            </TinybirdProvider>
          </SidebarProvider>
          <Toaster closeButton />
        </Providers>
      </body>
    </html>
  );
}
